# SetJointGainD service
# Sets the D gain value for one joint

# Request
float32 gain_d  # Enter D Gain
int32 joint_number  # Enter the joint number
---
# Response
int32 result  # DG_RESULT enum value