# SetJointGainPID service
# Set the maximum values for the P, I, and D gains and error integrals for one joint

# Request
float32 gain_p  # Enter P Gain
float32 gain_d  # Enter the D gain
float32 gain_i  # Enter the I gain
float32 i_limit  # Setting the Error Integral Maximum
int32 joint_number  # Enter the joint number
---
# Response
int32 result  # DG_RESULT enum value