# SetJointGainIAll service
# Sets the I-gain value and error integral maximum for all joints

# Request
float32[20] gain_i  # Enter the I gain for all joints
float32[20] i_limit  # Setting the Error Integral Maximum for all joints
---
# Response
int32 result  # DG_RESULT enum value