# SetTCPGainPIDFinger service
# Set the maximum values for P, I, D gain and error integration for one finger for gripper TCP position control

# Request
float32[6] gain_p  # Enter P Gain for each axis
float32[6] gain_d  # Enter D Gain for each axis
float32[6] gain_i  # Enter I Gain for each axis
float32[6] i_limit  # Enter the maximum value of the error integral for each axis
int32 finger_number  # Enter the finger number
---
# Response
int32 result  # DG_RESULT enum value