# DiagnosisSystem message
# Struct for checking result values in diagnostic functions

# Processes that are performing diagnostic functions
int32 process

# Check order for each diagnostic feature
int32 step

# Results when checking intermodule communication
int32 joint_id

# Resulting values when checking communication cycles
int32 period

# Result values when examining joints
int32 joint

# Resulting values when temperature is checked
int32 temperature